=== landlock-lsm/landlockconfig/schema/landlockconfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Landlock security policy configuration schema",
  "type": "object",
  "definitions": {
    "uint64": {
      "type": "integer",
      "minimum": 0,
      "maximum": 18446744073709551615
    },
    "abi": {
      "type": "integer",
      "minimum": 1,
      "maximum": 2147483647
    },
    "accessFs": {
      "type": "string",
      "enum": [
        "abi.all",
        "abi.read_execute",
        "abi.read_write",
        "execute",
        "write_file",
        "read_file",
        "read_dir",
        "remove_dir",
        "remove_file",
        "make_char",
        "make_dir",
        "make_reg",
        "make_sock",
        "make_fifo",
        "make_block",
        "make_sym",
        "refer",
        "truncate",
        "ioctl_dev"
      ]
    },
    "accessNet": {
      "type": "string",
      "enum": [
        "abi.all",
        "bind_tcp",
        "connect_tcp"
      ]
    },
    "scope": {
      "type": "string",
      "enum": [
        "abi.all",
        "abstract_unix_socket",
        "signal"
      ]
    }
  },
  "properties": {
    "abi": {
      "$ref": "#/definitions/abi"
    },
    "variable": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "literal": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      }
    },
    "ruleset": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "handledAccessFs": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/definitions/accessFs"
            }
          },
          "handledAccessNet": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/definitions/accessNet"
            }
          },
          "scoped": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/definitions/scope"
            }
          }
        },
        "minProperties": 1,
        "additionalProperties": false
      }
    },
    "pathBeneath": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "allowedAccess": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/definitions/accessFs"
            }
          },
          "parent": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "allowedAccess",
          "parent"
        ],
        "additionalProperties": false
      }
    },
    "netPort": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "allowedAccess": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/definitions/accessNet"
            }
          },
          "port": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/definitions/uint64"
            }
          }
        },
        "required": [
          "allowedAccess",
          "port"
        ],
        "additionalProperties": false
      }
    }
  },
  "anyOf": [
    {
      "required": [
        "variable"
      ]
    },
    {
      "required": [
        "ruleset"
      ]
    },
    {
      "required": [
        "pathBeneath"
      ]
    },
    {
      "required": [
        "netPort"
      ]
    }
  ],
  "additionalProperties": false
}

=== landlock-lsm/landlockconfig/examples/mini-write-tmp.json
{
  "abi": 5,
  "ruleset": [
    {
      "handledAccessFs": [
        "abi.all"
      ],
      "handledAccessNet": [
        "bind_tcp"
      ]
    }
  ],
  "pathBeneath": [
    {
      "allowedAccess": [
        "abi.read_execute"
      ],
      "parent": [
        ".",
        "/bin",
        "/lib",
        "/usr",
        "/dev",
        "/etc",
        "/proc"
      ]
    },
    {
      "allowedAccess": [
        "abi.read_write"
      ],
      "parent": [
        "/tmp"
      ]
    }
  ],
  "netPort": [
    {
      "allowedAccess": [
        "bind_tcp"
      ],
      "port": [
        80,
        443
      ]
    }
  ]
}
